language: java
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

before_install:
  - chmod +x ./gradlew

install:
  - ./gradlew --no-daemon assemble

script:
  - ./gradlew --no-daemon test
