language: java
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
services:
  - postgresql

before_install:
  - psql -c "create user cuba with superuser password 'cuba';" -U postgres
  - chmod +x ./gradlew
  - ./gradlew --no-daemon createDb createTestDb

install:
  - ./gradlew --no-daemon assemble

script:
  - ./gradlew --no-daemon test
